### ISSUE TITLE
ThumbCreator missing

### ISSUE THREAD

**Issue by frdbr** [flathub/org.kde.kdenlive#118]
Thumbnail previews are missing due to [ThumbCreator](https://api.kde.org/frameworks/kio/html/classThumbCreator.html) not found. Terminal output: 
`kf.service.services: KServiceTypeTrader: serviceType "ThumbCreator" not found`

![image](https://user-images.githubusercontent.com/77309092/114709271-bd846d00-9d02-11eb-9aad-5e6b76b076d3.png)

**Comment by tsdgeos** [comment]
thumbcreator is provided by kio-extras. But i am going to guess that we should probably add it to the sdk? After all it's something we expect to work in all open dialogs?

What do you think @aleixpol @travier ?

**Comment by frdbr** [comment]
> After all it's something we expect to work in all open dialogs?

Definitely something our users expect to work out of the box.

**Comment by travier** [comment]
That's a good question. I'd have to give a try on Gwenview to see how it looks.

**Comment by tsdgeos** [comment]
Do you get previews on the file open dialog too?

**Comment by travier** [comment]
Yes

**Comment by travier** [comment]
Depending on the dialog, Kdenlive uses an internal open dialog or the portal open dialog (I noticed this can be noticed with the different theme in use). No strong opinion here. We can add kio-extras to Kdenlive, that should be enough but adding it to the SDK isn't wrong either.

**Comment by jlskuz** [comment]
Is there anything special I need to be aware of a build flag or something? (Unfortunately I can't find any kind of doc, readme,… for `kio-extras`) I tried to add it and build it locally

1. on the SDK
2. directly to Kdenlive's manifest

but in both situation the error is still the same and ThumbCreator is not working… 

This is what I tried (on the SDK after `breeze-icons` and on Kdenlive beetween `mlt` and `kdenlive`)
```json        
{
    "name": "kio-extras",
    "buildsystem": "cmake-ninja",
    "config-opts": [ "-DBUILD_TESTING=OFF" ],
    "sources": [ { "type": "git", "url": "https://invent.kde.org/network/kio-extras.git", "branch": "v21.04.2" } ]
},
```

**Comment by tsdgeos** [comment]
That should be enough, *but* you may be getting hit by the fact that flatpak mounts all files as if created on January 1st 1970, so when you add new KDE plugins they aren't found because the check of "are there new plugins since i last created the cache" always says no.

Does manually removing the file in your $HOME/.var/app/org.kde.kdenlive/cache/ksycoca5_* help?

**Comment by jlskuz** [comment]
Yes that indeed solves the problem! But how can we workaround that for the user?

**Comment by tsdgeos** [comment]
Damn, i should have asked you to keep the old file so we could try to test if the potential fixes actually fix the issue :D 

Maybe you can clear the cache file again, install the old version, run it, install the new version again and confirm it still fails? I guess it should

There is this untested patch http://mail.kde.org/pipermail/kde-frameworks-devel/attachments/20201212/030dfc19/attachment.bin for kservice that could fix it. Would you be available to rebuild the platform and see if it helps? 

See https://mail.kde.org/pipermail/kde-frameworks-devel/2020-December/114964.html and https://lists.freedesktop.org/archives/flatpak/2020-November/002057.html for more info around these things

**Comment by jlskuz** [comment]
I went back to the old version and it happened again until I deleted the cache. I kept the old file and if I copy it back the problem occurs again. So everything as you expected…

I also rebuild the platform with the patch applied and it seems to work. After I installed the patched version the problem was gone without touching the cache file…

**Comment by jlskuz** [comment]
@tsdgeos  Should we apply the Flatpak patch only in the runtime or to KService directly?

**Comment by tsdgeos** [comment]
Ok, that's really good news, thanks for the testing, let me bring this up again in the kde-frameworks-devel mailing list and see if the devels prefer that we patch it in the platform or merge it directly in kservice

**Comment by jlskuz** [comment]
Okay! In the meanwhile I opened a MR on the runtime to add `kio-extras`: https://invent.kde.org/packaging/flatpak-kde-runtime/-/merge_requests/51

**Comment by jlskuz** [comment]
My merge request to add `kio-extras` has now been merged and will be published on the runtime with the next bigger change. Also the patch for `KService` has been [applied](https://invent.kde.org/frameworks/kservice/-/commit/d0b34343bfc75a7f245df07ab0459a3a7d6bab8d) and will be in KF 5.84

Even if this is not applied yet, it has been fixed and I am closing this issue

**Comment by kimariterikishi** [comment]
> My merge request to add `kio-extras` has now been merged and will be published on the runtime with the next bigger change. Also the patch for `KService` has been [applied](https://invent.kde.org/frameworks/kservice/-/commit/d0b34343bfc75a7f245df07ab0459a3a7d6bab8d) and will be in KF 5.84
> 
> Even if this is not applied yet, it has been fixed and I am closing this issue

Thank you for installing the kio-extras package

sudo apt-get install kio-extras

fixed the Kaffeine application bug (not Flatpak):

[Warning ] kf.service.services: KServiceTypeTrader: serviceType "ThumbCreator" not found

**Comment by bphd** [comment]
In addition to Dolphin I've got
*  imath-3.1.3
-  kactivities-stats-5.108.0
*   kdnssd-5.108.0
-   kdsoap-2.0.0
*   openexr-3.1.3
-   kio-extras-23.04.3

And I still get `kf.service.services: KServiceTypeTrader: serviceType "ThumbCreator" not found`

**Comment by kimariterikishi** [comment]
> And I still get `kf.service.services: KServiceTypeTrader: serviceType "ThumbCreator" not found`

Try my earlier suggestion (hidden for some reason - which is essentially an expression of thanks):

`sudo apt-get install kio-extras`

Doesn't work for you?

**Comment by travier** [comment]
All of the recent comments are either off of topic and missing a lot of information for us to understand the issue. Please open a new issue with more details.
